export enum ERoutePath {
  HOME = '/',
  LOGIN = '/login',
  REGISTER = '/register',
  FORGOT_PASSWORD = '/forgot-password',
  RESET_PASSWORD = '/reset-password',
  PROFILE = '/profile',
  PROFILE_ORDERS = '/profile/orders',
  PROFILE_ORDERS_ID = '/profile/orders/:id',
  INGREDIENT_ID = '/ingredient/:id',
  ORDERS = '/orders',
  NOT_FOUNT = '/not-fount',
  FEED = '/feed',
  FEED_ID = '/feed/:id',
}
